name: "Deployment"
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          start: npm start
          wait-on: "http://localhost:3000"
  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/now-deployment@v2
        with:
          now-args: "--prod"
          now-org-id: ${{ secrets.ORG_ID }}
          now-project-id: ${{ secrets.PROJECT_ID }}
          zeit-token: ${{ secrets.ZEIT_TOKEN }}
